#!/bin/bash

set -e

. init-env-arch "$1"

#pushd kicadapp
pushd pcbnewapp

rm -rf "pcbnew_${CONF_ANDROID_ARCH}"
mkdir -p "pcbnew_${CONF_ANDROID_ARCH}"
pushd "pcbnew_${CONF_ANDROID_ARCH}"

mkdir -p ./assets/share/

cp -r "${CONF_SYSROOT_USR}/share/kicad/"* ./assets/share/

# Copy Python stdlib
mkdir -p ./assets/share/lib/
cp -r "${CONF_SYSROOT_USR}"/lib/python*/ ./assets/share/lib/

# Remove unneeded Python files
rm -rf ./assets/share/lib/python*/test/
rm -rf ./assets/share/lib/python*/idlelib/
rm -rf ./assets/share/lib/python*/pydoc_data/
find ./assets/share/lib/python*/ -type f -name '*.py[co]' -delete -o -type d -name __pycache__ -delete

# Remove unneeded demos
rm -rf ./assets/share/demos/tiny_tapeout/


mkdir -p "./libs/${CONF_ANDROID_ARCH}/"

for binary in libkicad_${CONF_ANDROID_ARCH}.so libpcbnew_${CONF_ANDROID_ARCH}.so libkiface_eeschema.so libkiface_pcbnew.so libkiface_gerbview.so; do
    dep_cmd="${NDKDEPENDS} \
        -L ${CONF_SYSROOT_USR}/lib \
        -L ${QT_CUSTOM_DIR}/lib \
        -L ${ANDROID_TOOLCHAIN_PATH}/sysroot/usr/lib/aarch64-linux-android/ \
        ${CONF_SYSROOT_USR}/bin/${binary}"

    echo "CMD: $dep_cmd"
    
    bin_deps="$(${dep_cmd})"
    
    echo "${binary} dependencies: ${bin_deps}"
    
    all_deps="${all_deps}\n${bin_deps}"
done

all_deps=$(echo -e "${all_deps}" | sort -u)

echo "All Dependencies: ${all_deps}"

for dep_name in $all_deps
do
    lib_path="${CONF_SYSROOT_USR}/lib/${dep_name}"
    bin_path="${CONF_SYSROOT_USR}/bin/${dep_name}"
    qt_path="${QT_CUSTOM_DIR}/lib/${dep_name}"

    [ -f "${lib_path}" ] && cp -v "${lib_path}" "./libs/${CONF_ANDROID_ARCH}/"
    [ -f "${bin_path}" ] && cp -v "${bin_path}" "./libs/${CONF_ANDROID_ARCH}/"
    [ -f "${qt_path}" ] && cp -v "${qt_path}" "./libs/${CONF_ANDROID_ARCH}/"
done

# for plugin in "${QT_CUSTOM_DIR}"/plugins/*/*
# do
#     cp -v "${plugin}" "./libs/${CONF_ANDROID_ARCH}/"
# done

popd

popd
