#!/bin/bash

set -e

. init-env

pushd Boost-for-Android

./build-android.sh --arch=x86_64,arm64-v8a --with-iconv --with-libraries=locale ${ANDROID_NDK_ROOT}

for android_arch in $CONF_ANDROID_ARCHES; do
    cp -r build/out/${android_arch}/* ${CONF_SYSROOT}/${android_arch}/usr
    cp -r libiconv-libicu-android/${android_arch}/lib ${CONF_SYSROOT}/${android_arch}/usr/
    cp -r libiconv-libicu-android/${android_arch}/include ${CONF_SYSROOT}/${android_arch}/usr/
    cp -r libiconv-libicu-android/${android_arch}/bin ${CONF_SYSROOT}/${android_arch}/usr/
    cp -r libiconv-libicu-android/${android_arch}/sbin ${CONF_SYSROOT}/${android_arch}/usr/
done

popd
