#!/bin/bash

set -e

. init-env-arch $1

pushd cairo


cat > android-cross-file-${CONF_ANDROID_ARCH}.txt <<EOF
[constants]
ndk_path    = '${ANDROID_NDK_ROOT}'
toolchain   = '${ANDROID_TOOLCHAIN_PATH}/bin/${CONF_COMPILER_ARCH}-linux-android'
api         = '${CONF_ANDROID_LEVEL}'

[host_machine]
system      = 'android'
cpu_family  = '${CONF_COMPILER_ARCH}'
cpu         = '${CONF_COMPILER_ARCH}'
endian      = 'little'

[properties]
sys_root        = ndk_path + '/sysroot'

[binaries]
c           = toolchain + api + '-clang'
cpp         = toolchain + api + '-clang++'
strip       = toolchain + '-strip'
EOF

meson setup --prefix / --buildtype release --cross-file android-cross-file-${CONF_ANDROID_ARCH}.txt -Dpixman:a64-neon=disabled build_${CONF_ANDROID_ARCH}
meson compile --verbose -C build_${CONF_ANDROID_ARCH}
meson install --destdir .output -C build_${CONF_ANDROID_ARCH}

cp -r build_${CONF_ANDROID_ARCH}/.output/* ${CONF_SYSROOT_USR}/

popd
