#!/bin/bash

set -e

. init-env-arch $1

pushd cairo


cat > "android-cross-file-${CONF_ANDROID_ARCH}.txt" <<EOF
[constants]
ndk_path    = '${ANDROID_NDK_ROOT}'
toolchain   = '${ANDROID_TOOLCHAIN_PATH}/bin/${CONF_COMPILER_ARCH}-linux-android'
api         = '${CONF_ANDROID_LEVEL}'

[host_machine]
system      = 'android'
cpu_family  = '${CONF_COMPILER_ARCH}'
cpu         = '${CONF_COMPILER_ARCH}'
endian      = 'little'

[properties]
sys_root          = '${CONF_SYSROOT_ARCH}'
pkg_config_libdir = '${CONF_SYSROOT_USR}/lib/pkgconfig'

[binaries]
c           = toolchain + api + '-clang'
cpp         = toolchain + api + '-clang++'
strip       = toolchain + '-strip'
as          = 'llvm-as'
ar          = 'llvm-ar'
ranlib      = 'llvm-ranlib'
pkg-config  = 'pkg-config'
cmake       = 'cmake'
EOF

meson setup --prefix "/usr" --buildtype release \
    --cross-file "android-cross-file-${CONF_ANDROID_ARCH}.txt" \
    "build_${CONF_ANDROID_ARCH}" \
    --pkg-config-path="${CONF_SYSROOT_USR}/lib/pkgconfig" \
    --cmake-prefix-path="${CONF_SYSROOT_USR}" \
    -Dauto_features=disabled \
    -Dpixman:a64-neon=disabled \
    -Dfreetype=enabled \
    -Dzlib=enabled \
    -Dpng=enabled
    
meson compile -C "build_${CONF_ANDROID_ARCH}"
meson install --destdir .output -C "build_${CONF_ANDROID_ARCH}"

cp -r "build_${CONF_ANDROID_ARCH}/.output/"* "${CONF_SYSROOT_ARCH}/"

popd
