#!/bin/bash

set -e

. init-env

#for android_arch in $CONF_ANDROID_ARCHES; do
#    ./curl-build-arch $android_arch
#done

export NDK="${ANDROID_NDK_ROOT}"
export HOST_TAG=linux-x86_64
export MIN_SDK_VERSION=23

#export CFLAGS="-Os"
#export LDFLAGS="-Wl,-Bsymbolic"

pushd openssl-curl-android

./build.sh

popd
