#!/bin/bash

set -e

. init-env-arch $1

pushd libgit2

mkdir -p "build_${CONF_ANDROID_ARCH}"
pushd "build_${CONF_ANDROID_ARCH}"

export CPPFLAGS="-I${CONF_SYSROOT_USR}/include"
export CXXFLAGS="${CPPFLAGS}"
export CFLAGS="${CPPFLAGS} -Dinline=__inline__"

cmake \
    -DCMAKE_TOOLCHAIN_FILE="${CONF_BASE_PATH}/android_toolchain.cmake" \
    -DANDROID_PLATFORM="${ANDROID_NDK_PLATFORM}" \
    -DANDROID_ABI="${CONF_ANDROID_ARCH}" \
    -DANDROID_STL="none" \
    -DCMAKE_FIND_ROOT_PATH="${CONF_SYSROOT_ARCH}" \
    -DCMAKE_INSTALL_PREFIX="/usr" \
    -DCMAKE_C_FLAGS="${CFLAGS}" \
    -DCMAKE_CXX_FLAGS="${CXXFLAGS}" \
    -DBUILD_TESTS=OFF \
    -DUSE_HTTPS=OpenSSL \
    ..

cmake --build . -j 24
make DESTDIR="${CONF_SYSROOT_ARCH}" install

popd

popd
