#!/bin/bash

set -e

. init-env-arch $1

export LIBRARY_PATH="${GL4ES_ROOT}/libs/${CONF_ANDROID_ARCH}"

pushd glu

cat > android-cross-file-${CONF_ANDROID_ARCH}.txt <<EOF
[constants]
ndk_path    = '${ANDROID_NDK_ROOT}'
toolchain   = '${ANDROID_TOOLCHAIN_PATH}/bin/${CONF_COMPILER_ARCH}-linux-android'
api         = '${CONF_ANDROID_LEVEL}'

[host_machine]
system      = 'android'
cpu_family  = '${CONF_COMPILER_ARCH}'
cpu         = '${CONF_COMPILER_ARCH}'
endian      = 'little'

[properties]
sys_root          = '${CONF_SYSROOT_ARCH}'
pkg_config_libdir = '${CONF_SYSROOT_USR}/lib/pkgconfig'

[binaries]
c           = toolchain + api + '-clang'
cpp         = toolchain + api + '-clang++'
strip       = toolchain + '-strip'
as          = 'llvm-as'
ar          = 'llvm-ar'
ranlib      = 'llvm-ranlib'
pkg-config  = 'pkg-config'
cmake       = 'cmake'
EOF

echo "Running meson setup for build_${CONF_ANDROID_ARCH}"

meson setup \
    --prefix "/usr" \
    --buildtype release \
    --cross-file "android-cross-file-${CONF_ANDROID_ARCH}.txt" \
    "build_${CONF_ANDROID_ARCH}" \
    -Dgl_provider=gl \
    -Dgl4es_root="${GL4ES_ROOT}" \
    -Dc_args="-Wno-tautological-undefined-compare -Wno-self-assign" \
    -Dcpp_args="-Wno-tautological-undefined-compare -Wno-self-assign" --wipe
    
meson compile -C "build_${CONF_ANDROID_ARCH}"
meson install --destdir .output -C "build_${CONF_ANDROID_ARCH}"

cp -r "build_${CONF_ANDROID_ARCH}/.output/"* "${CONF_SYSROOT_ARCH}/"

popd
