#!/bin/bash

set -e

. init-env

echo " ** PATH **: $PATH"
x86_64-linux-android28-clang --version

echo "*** ${ANDROID_TOOLCHAIN_PATH}/bin"
ls -la "${ANDROID_TOOLCHAIN_PATH}/bin"
echo "***"


pushd icu/source

build_dir=build_host

mkdir -p "$build_dir"
pushd "$build_dir"

../configure 

make -j24

popd
popd

echo " ** PATH **: $PATH"

for android_arch in $CONF_ANDROID_ARCHES; do
    ./icu-build-arch $android_arch
done
