#!/bin/bash

export CONF_ANDROID_ARCH=$1

case $CONF_ANDROID_ARCH in

    arm64-v8a)
        export CONF_COMPILER_ARCH="aarch64"
    ;;

    *)
        export CONF_COMPILER_ARCH="$CONF_ANDROID_ARCH"
    ;;
esac

export WX_CONFHOST="${CONF_COMPILER_ARCH}-linux-android${CONF_ANDROID_LEVEL}"

export CONF_SYSROOT_ARCH="${CONF_SYSROOT}/${CONF_ANDROID_ARCH}"
export CONF_SYSROOT_USR="${CONF_SYSROOT_ARCH}/usr"
mkdir -p ${CONF_SYSROOT_USR}
mkdir -p ${CONF_SYSROOT_USR}/lib
mkdir -p ${CONF_SYSROOT_USR}/include
mkdir -p ${CONF_SYSROOT_USR}/bin
