#!/bin/bash

export CONF_ANDROID_ARCH=$1

case $CONF_ANDROID_ARCH in

    arm64-v8a)
        export CONF_COMPILER_ARCH="aarch64"
    ;;

    *)
        export CONF_COMPILER_ARCH="$CONF_ANDROID_ARCH"
    ;;
esac

#export CC="${CONF_COMPILER_ARCH}-linux-android${CONF_ANDROID_LEVEL}-clang"
#export CXX="${CONF_COMPILER_ARCH}-linux-android${CONF_ANDROID_LEVEL}-clang++"
#export AR="${CONF_COMPILER_ARCH}-linux-android-ar"
#export AS="${CONF_COMPILER_ARCH}-linux-android-as"
#export LD=${CC}
#export RANLIB="${CONF_COMPILER_ARCH}-linux-android-ranlib"
#export STRIP="${CONF_COMPILER_ARCH}-linux-android-strip"
#export OBJDUMP="${CONF_COMPILER_ARCH}-linux-android-objdump"

export QT_CUSTOM_DIR="/media/alex/Build/qt6-android/install_${CONF_ANDROID_ARCH}"

export WX_CONFHOST="${CONF_COMPILER_ARCH}-linux-android${CONF_ANDROID_LEVEL}"

export CONF_SYSROOT_ARCH="${CONF_SYSROOT}/${CONF_ANDROID_ARCH}"
export CONF_SYSROOT_USR="${CONF_SYSROOT_ARCH}/usr"
mkdir -p ${CONF_SYSROOT_USR}
mkdir -p ${CONF_SYSROOT_USR}/lib
mkdir -p ${CONF_SYSROOT_USR}/include
mkdir -p ${CONF_SYSROOT_USR}/bin
