#!/bin/bash

BASE_PATH="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

export ANDROID_NDK_ROOT="$HOME/android-ndk-r21e"
export ANDROID_SDK_ROOT="$HOME/Android/Sdk"

export QT5_CUSTOM_DIR="${BASE_PATH}/qt/5.15.2/android"
export PATCHELF="${BASE_PATH}/patchelf"
export WX_ROOT="${BASE_PATH}/wxWidgets"
export CONF_SYSROOT="${BASE_PATH}/sysroot"
export NDKDEPENDS="${BASE_PATH}/ndk-depends"

export WX_VERSION=3.3
export WX_INC_DIR=${WX_ROOT}/include

export CONF_ANDROID_ARCHES="x86_64 arm64-v8a"
export CONF_ANDROID_LEVEL=28
export ANDROID_NDK_PLATFORM="android-${CONF_ANDROID_LEVEL}"

export PATH=${ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt/linux-x86_64/bin:${QT5_CUSTOM_DIR}/bin:$PATH

mkdir -p ${CONF_SYSROOT}
