#!/bin/bash

set -e

. init-env-arch $1

export CC="${CONF_COMPILER_ARCH}-linux-android${CONF_ANDROID_LEVEL}-clang"
export CXX="${CONF_COMPILER_ARCH}-linux-android${CONF_ANDROID_LEVEL}-clang++"

pushd ngspice

release=build-${CONF_ANDROID_ARCH}

mkdir -p "./$release"

pushd "./$release"

export ac_cv_lib_pthread_pthread_create=yes

#export CXXFLAGS="-Wno-unused-command-line-argument -Wno-sign-conversion -Wno-float-conversion"

VERBOSE=1 ../configure \
            --build="$(../config.guess)" \
            --host="$WX_CONFHOST" \
            --prefix="/usr" \
            --exec-prefix="/usr" \
            --with-ngshared --enable-cider --disable-debug

popd

make -C "./$release" -j24
make DESTDIR="${CONF_SYSROOT_ARCH}" -C "./$release" -j24 install

popd
