#!/bin/bash

set -e

. init-env-arch $1

export CC="${CONF_COMPILER_ARCH}-linux-android${CONF_ANDROID_LEVEL}-clang"
export CXX="${CONF_COMPILER_ARCH}-linux-android${CONF_ANDROID_LEVEL}-clang++"

pushd ngspice

release=build-android-${CONF_ANDROID_ARCH}
dst=${PWD}/.output_${CONF_ANDROID_ARCH}

mkdir -p "$dst"
mkdir -p "./$release"

pushd "./$release"

export ac_cv_lib_pthread_pthread_create=yes

#export CXXFLAGS="-Wno-unused-command-line-argument -Wno-sign-conversion -Wno-float-conversion"

VERBOSE=1 ../configure \
            --build=$(../config.guess) \
            --host="$WX_CONFHOST" \
            --prefix="$dst" \
            --exec-prefix="$dst" \
            --with-ngshared --enable-xspice --enable-cider --disable-debug

popd

make -C "./$release" -j24
make -C "./$release" -j24 install

cp -r ${dst}/* ${CONF_SYSROOT_USR}/

popd
