#!/bin/bash

set -e

. init-env-arch $1

export CC="${CONF_COMPILER_ARCH}-linux-android${CONF_ANDROID_LEVEL}-clang"
export CXX="${CONF_COMPILER_ARCH}-linux-android${CONF_ANDROID_LEVEL}-clang++"

pushd unixODBC

build_dir=build_${CONF_ANDROID_ARCH}

mkdir -p "$build_dir"
pushd "$build_dir"

../configure \
    --host="${WX_CONFHOST}" \
    --prefix=""

make DESTDIR="${CONF_SYSROOT_USR}" -j24 install

#cp -r .output/* ${CONF_SYSROOT_USR}/

popd

popd
