#!/bin/bash

set -e

. init-env-arch $1

case $CONF_ANDROID_ARCH in

    arm64-v8a)
        export OPENSSL_TARGET="android-arm64"
    ;;

    x86_64)
        export OPENSSL_TARGET="android-x86_64"
    ;;

    *)
        echo "Unsuppoorted target"
    ;;
esac

export CC="${CONF_COMPILER_ARCH}-linux-android${CONF_ANDROID_LEVEL}-clang"
export CXX="${CONF_COMPILER_ARCH}-linux-android${CONF_ANDROID_LEVEL}-clang++"
export AR="llvm-ar"
export AS="llvm-as"
export RANLIB="llvm-ranlib"
export STRIP="llvm-strip"

export CFLAGS="-Os -ffunction-sections -fdata-sections -fno-unwind-tables -fno-asynchronous-unwind-tables -flto -gdwarf"
export LDFLAGS="-Wl,-s -Wl,-Bsymbolic" # -Wl,--gc-sections

pushd openssl

./Configure "${OPENSSL_TARGET}" --prefix="/usr" \
    no-tests no-apps no-sm2 no-cms no-cmp no-argon2 no-http no-legacy \
    no-blake2 no-ocsp no-dynamic-engine no-dso no-asm

make clean
make CALC_VERSIONS="SHLIB_COMPAT=; SHLIB_SOVER=" -j24
make DESTDIR="${CONF_SYSROOT_ARCH}" install_sw
make clean

popd
