#!/bin/bash

set -e

. init-env-arch $1

export CC="${CONF_COMPILER_ARCH}-linux-android${CONF_ANDROID_LEVEL}-clang"
export CXX="${CONF_COMPILER_ARCH}-linux-android${CONF_ANDROID_LEVEL}-clang++"
export AR="llvm-ar"
export AS="llvm-as"
export RANLIB="llvm-ranlib"
export READELF="llvm-readelf"

export CFLAGS="-fPIC"
export CPPFLAGS="-fPIC"

pushd python

build_dir=build_${CONF_ANDROID_ARCH}

mkdir -p "$build_dir"
pushd "$build_dir"

../configure \
    --build=x86_64-pc-linux-gnu \
    --host="${WX_CONFHOST}" \
    --prefix="/usr" \
    --disable-ipv6 \
    --enable-shared \
    ac_cv_have_long_long_format=yes ac_cv_file__dev_ptmx=no ac_cv_file__dev_ptc=no

make DESTDIR="${CONF_SYSROOT_ARCH}" INSTSONAME="libpython\$(LDVERSION).so" -j24 install

popd

popd
