#!/bin/bash

set -e

. init-env-arch $1

BASE_PATH="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

export CC="${CONF_COMPILER_ARCH}-linux-android${CONF_ANDROID_LEVEL}-clang"
export CXX="${CONF_COMPILER_ARCH}-linux-android${CONF_ANDROID_LEVEL}-clang++"
export AR="llvm-ar"
export AS="llvm-as"
export RANLIB="llvm-ranlib"
export READELF="llvm-readelf"
export STRIP="llvm-strip"

export CFLAGS="-fPIC"
export CPPFLAGS="-fPIC"

export PKG_CONFIG_SYSROOT_DIR="${CONF_SYSROOT_ARCH}"
export PKG_CONFIG_PATH="${CONF_SYSROOT_USR}/lib/pkgconfig"
export PKG_CONFIG_LIBDIR="${CONF_SYSROOT_USR}/lib/pkgconfig"

pushd python

build_dir=build_${CONF_ANDROID_ARCH}

mkdir -p "$build_dir"
pushd "$build_dir"

# mimalloc throws SIGSYS in prim.c at mi_prim_open("/proc/sys/vm/overcommit_memory", O_RDONLY); on Android 9

../configure \
    --build=x86_64-pc-linux-gnu \
    --with-build-python="${BASE_PATH}/python/install_host/bin/python3" \
    --host="${WX_CONFHOST}" \
    --prefix="/usr" \
    --disable-ipv6 \
    --enable-shared \
    --without-mimalloc \
    --without-doc-strings \
    --without-ensurepip \
    --without-static-libpython

make clean

make DESTDIR="${CONF_SYSROOT_ARCH}" -j24 install

"$STRIP" -s "${CONF_SYSROOT_USR}"/lib/libpython*.so
"$STRIP" -s "${CONF_SYSROOT_USR}"/lib/python*/lib-dynload/*.so

popd

popd
