#!/bin/bash

set -e

. init-env-arch "$1"

pushd wxWidgets

mkdir -p "build_${CONF_ANDROID_ARCH}"
pushd "build_${CONF_ANDROID_ARCH}"

#-I${CONF_SYSROOT_USR}/include
export CPPFLAGS=""
export CXXFLAGS="${CPPFLAGS}"
export CFLAGS="${CPPFLAGS}"
export LDFLAGS="-llog -Wl,-rpath-link=${CONF_SYSROOT_USR}/lib"

cmake \
    -DCMAKE_TOOLCHAIN_FILE="${CONF_BASE_PATH}/android_toolchain.cmake" \
    -DCMAKE_INSTALL_PREFIX="/usr" \
    -DANDROID_PLATFORM="${ANDROID_NDK_PLATFORM}" \
    -DANDROID_ABI="${CONF_ANDROID_ARCH}" \
    -DCMAKE_FIND_ROOT_PATH="${CONF_SYSROOT_ARCH};${QT_CUSTOM_DIR}" \
    -DCMAKE_EXE_LINKER_FLAGS="${LDFLAGS}" \
    -DCMAKE_MODULE_LINKER_FLAGS="${LDFLAGS}" \
    -DCMAKE_SHARED_LINKER_FLAGS="${LDFLAGS}" \
    -DCMAKE_C_FLAGS="${CFLAGS}" \
    -DCMAKE_CXX_FLAGS="${CXXFLAGS}" \
    -DwxBUILD_TOOLKIT=qt \
    -DwxBUILD_TESTS=OFF \
    -DwxUSE_UIACTIONSIMULATOR=OFF \
    -DwxUSE_SOUND=OFF \
    -DwxUSE_IMAGE=ON \
    -DwxUSE_HTML=ON \
    -DwxUSE_STACKWALKER=OFF \
    -DwxUSE_SECRETSTORE=OFF \
    -DwxUSE_LIBICONV=OFF \
    -DwxUSE_XLOCALE=OFF \
    -DwxUSE_INTL=ON \
    -DwxUSE_OPENGL=ON \
    -DwxUSE_PRIVATE_FONTS=ON \
    -DwxUSE_REGEX=sys \
    -DwxUSE_LIBMSPACK=OFF \
    -DwxUSE_LIBJPEG=builtin \
    -DwxUSE_LIBPNG=sys \
    -DwxUSE_LIBTIFF=sys \
    -DCMAKE_FIND_DEBUG_MODE=OFF \
    ..

cmake --build . -j 24
make DESTDIR="${CONF_SYSROOT_ARCH}" install/strip
make clean

popd

popd
