#!/bin/bash

set -e

if [ $CONF_BUILD_STATIC == "1" ]; then
    EXTRACONF=--disable-shared
fi

../configure --with-qt --build=x86_64-unknown-linux-gnu --host=$WX_CONFHOST --without-subdirs --disable-arttango --enable-image --disable-dragimage --disable-sockets --with-libcurl=no --with-libtiff=no --disable-utf8 --enable-secretstore=no --disable-sys-libs --with-zlib=sys --with-opengl=no --enable-detect_sm=no --with-cairo=no --with-libiconv=no $EXTRACONF LDFLAGS="-llog" CPPFLAGS="-DANDROID"

