name: Android build
run-name: Android build
on: [push]

env:
  QT_VERSION: "6.6.2"

jobs:
  build-android:
    runs-on: ubuntu-22.04
    steps:
      # Install Meson
      - name: Install meson
        run: sudo pip3 install --upgrade meson

      # Install Java
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Android environment
      - name: Setup Android environment
        uses: android-actions/setup-android@v3
        with:
          log-accepted-android-sdk-licenses: false

      - name: Install Android SDK / NDK / tools
        run: |
             sdkmanager "platforms;android-34"
             sdkmanager "ndk;25.2.9519653"
             sdkmanager "build-tools;34.0.0"

      # Install Qt (desktop & Android)
      - name: Install Qt (desktop)
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{env.QT_VERSION}}

      - name: Install Qt (Android x86_64)
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{env.QT_VERSION}}
          host: 'linux'
          target: 'android'
          arch: 'android_x86_64'

      - name: Install Qt (Android armv8)
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{env.QT_VERSION}}
          host: 'linux'
          target: 'android'
          arch: 'android_arm64_v8a'
      
      # Setup env
      - name: Setup env
        run: |
             echo "QT_HOST_PATH=/home/runner/work/${{ github.event.repository.name }}/Qt/${{env.QT_VERSION}}/gcc_64" >> $GITHUB_ENV
             echo "QT_TARGET_BASE=/home/runner/work/${{ github.event.repository.name }}/Qt/${{env.QT_VERSION}}" >> $GITHUB_ENV

      # Checkout repository (and submodules)
      - name: Checkout repository (and submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Fetch tarballs
        run: |
          mkdir -p OCCT && curl -L -o - 'https://codeload.github.com/Open-Cascade-SAS/OCCT/tar.gz/refs/tags/V7_8_0' | tar -xz --strip-components=1 -C OCCT
          mkdir -p libgit2 && curl -L -o - 'https://codeload.github.com/libgit2/libgit2/tar.gz/refs/tags/v1.8.0' | tar -xz --strip-components=1 -C libgit2
          mkdir -p ngspice && curl -L -o - 'https://altushost-swe.dl.sourceforge.net/project/ngspice/ng-spice-rework/42/ngspice-42.tar.gz' | tar -xz --strip-components=1 -C ngspice
          mkdir -p cairo && curl -L -o - 'https://gitlab.freedesktop.org/cairo/cairo/-/archive/02754405330989198548d1945b3c55566ba0c6b7/cairo-02754405330989198548d1945b3c55566ba0c6b7.tar.gz' | tar -xz --strip-components=1 -C cairo
          mkdir -p unixODBC && curl -L -o - 'ftp://ftp.unixodbc.org/pub/unixODBC/unixODBC-2.3.12.tar.gz' | tar -xz --strip-components=1 -C unixODBC

      - name: Patch GLU
        run: |
            cp _glu_meson.build glu/meson.build
            cp _glu_meson_options.txt glu/meson_options.txt

      - name: Build Application
        run: ./all.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: pcbnewapp/android/*.apk
